model:
  activation_gnn: ReLU
  activation_mlps_final: ReLU
  hid_gnn_layer_dim: 128
  hid_mlp_dim: 256
  k_pool_ratios:
  - 0.95
  - 0.95
  - 0.95
  dropout_gnn: 0.05
  dropout_mlps_final: 0.05
  adj_norm: row
training:
  lr: 0.002384572405954512
  epochs: 300
  batch_size: 32
  shuffle: true
  adam_weight_decay: 1.5156392708179834e-07
  num_train_trajs: 3
  mode: standard
  gamma_lr_scheduler: 0.9922635465387664
  random_seed: 42
  overfit_traj_id: 0
  overfit_time_idx:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  datapath: processed_data/data_world=radius_mesh=True_norm=standard_At=False
  model_path_out: model_out/
  amp: true
  move_all_to_device: true
