# Model hyperparameters
model:
  activation_gnn: "ELU"
  activation_mlps_final: "ELU"
  hid_gnn_layer_dim: 128 # 128
  hid_mlp_dim: 256 # 256
  k_pool_ratios: [0.95, 0.8, 0.7] # [0.9, 0.8, 0.7] [0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.8, 0.7]
  dropout_gnn: 0 # default = 0.1, overfit = 0
  dropout_mlps_final: 0 # default = 0.1, overfit = 0
  adj_norm: "row" # 'sym' | 'row'

# Training parameters
training:
  lr: 0.001 # default = 1e-4 good value 0.001
  epochs: 3
  batch_size: 10
  shuffle: False # False for overfitting
  adam_weight_decay: 0 # default: 1e-4 | overfit = 0
  num_train_trajs: 1
  mode: "None" # None or "overfit"
  gamma_lr_scheduler: 0.96 # lr_final = lr0 * gamma^epochs 0.9995 good value 0.9997
  random_seed: 42 # Seed for train/test split and any random operations
  overfit_traj_id: 0 # For overfit mode: which trajectory to use (null = use first available)
  overfit_time_idx: [0,1,2,3] # For overfit mode: which time step t to use (null = use all time steps from trajectory)
  # [13, 202, 302, 10, 11, 90, 321, 43]
  datapath: "processed_data/data_world=radius_mesh=True_norm=standard_At=False" # data_world=None_mesh=False_norm=standard_Ainv=True
  model_path_out: "model_out/"
  amp: True # enable automatic mixed precision training
  move_all_to_device: True
