data:
  include_mesh_pos: True
  normalization_method: "standard" # 'standard' or 'row'
  adj_norm: "row" # 'sym' | 'row' (applied to adjacency in preprocessing)
  max_trajs: 100
  valid_max_trajs: 3
  tfrecord_path: "raw_data/train.tfrecord"
  meta_path: "raw_data/meta.json"
  # Change output_dir as you wish, we keep track of the parameters in the config
  output_dir: "processed_data/data_world=radius_mesh=True_norm=standard_At=False"
  add_world_edges: "radius" # 'neighbours' or 'radius' or 'None'
  radius_world_edge: 0.03
  k_neighb: 1
  a_time_var: False